filebeat.prospectors:
- input_type: log
  enabled: true
  paths:
    - /tmp/logs/access.log
  document_type: access-log
  fields:
    type: access-log
# - input_type: log
#   paths:
#     - "/tmp/logs/50x.log"
#   document_type: error-log

output.logstash:
  enabled: true
  hosts: ['docker.for.mac.localhost:5044']
  worker: 1
  escape_html: true
  max_retries: 3
  backoff.max: 60s # max seconds to wait connection
  timeout: 30s # max seconds to wait logstash response
  bulk_max_size: 2048